language: node_js
node_js:
  - "4"
  - "6"

addons:
  postgresql: "9.6"

before_script: make db/create PGHOST=localhost PGUSER=postgres
script: make spec PGHOST=localhost PGUSER=postgres

notifications:
  email: ["andri@dot.ee"]
